version: "3"

services:
  main:
    container_name: proton_crm_main
    build: .
    command: python3 protoncrm/manage.py runserver 0.0.0.0:8000
    restart: always
    networks:
      - botnet
    env_file:
      - "protoncrm/.env"
    ports:
      - 8000:8000
    volumes:
      - .:/proton_crm

  notify:
    container_name: proton_crm_notify
    build:
      context: .
    command: python3 protoncrm/manage.py bot
    restart: always
    networks:
      - botnet
    env_file:
      - "protoncrm/.env"
    volumes:
      - .:/proton_crm

networks:
  botnet:
    driver: bridge